version: "3.8"
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    image: dev_image
    container_name: dev_ctr
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
